language: generic
dist: bionic

matrix:
        include:
                - env: DJANGO_SETTINGS_MODULE=xasdb.settings_sqlite_dev
                - env: DJANGO_SETTINGS_MODULE=xasdb.settings_mariadb_dev
                  addons:
                          mariadb: '10.4'
                  sudo: true

install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes
        - conda update -q conda
        - conda install django bokeh sqlparse
        - conda install -c conda-forge xraylib habanero Pillow django-cleanup
        # install xdi...
        - pushd $HOME
        - git clone -b XDI-autotools https://github.com/tschoonj/XAS-Data-Interchange
        - cd XAS-Data-Interchange/lib
        - autoreconf -fi
        - ./configure --prefix=$HOME/miniconda
        - make && make install
        - cd ../languages/python
        - python setup.py install
        - popd

script:
        - |
          if test -n "$TRAVIS_MARIADB_VERSION" ; then
                sudo mysql -u root -e "CREATE USER 'xas_db_usr'@'localhost' IDENTIFIED BY 'BS4_password';"
                sudo mysql -u root -e "GRANT ALL ON test_xasdb.* TO 'xas_db_usr'@'localhost'"
                export XASDB_MARIADB_PASSWORD=BS4_password
                conda install -c conda-forge -c defaults mysqlclient
          fi
        - cd xasdb ; python manage.py test -v 2


branches:
        only:
                - master

notifications:
        email:
                recipients:
                        - Tom.Schoonjans@me.com
                on_success: never
                on_failure: always
